package com.jerry.myframwork.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jerry.myframwork.bean.MyCurrencyPair;
import com.jerry.myframwork.bean.RecordBean;

import com.jerry.myframwork.greendao.MyCurrencyPairDao;
import com.jerry.myframwork.greendao.RecordBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myCurrencyPairDaoConfig;
    private final DaoConfig recordBeanDaoConfig;

    private final MyCurrencyPairDao myCurrencyPairDao;
    private final RecordBeanDao recordBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myCurrencyPairDaoConfig = daoConfigMap.get(MyCurrencyPairDao.class).clone();
        myCurrencyPairDaoConfig.initIdentityScope(type);

        recordBeanDaoConfig = daoConfigMap.get(RecordBeanDao.class).clone();
        recordBeanDaoConfig.initIdentityScope(type);

        myCurrencyPairDao = new MyCurrencyPairDao(myCurrencyPairDaoConfig, this);
        recordBeanDao = new RecordBeanDao(recordBeanDaoConfig, this);

        registerDao(MyCurrencyPair.class, myCurrencyPairDao);
        registerDao(RecordBean.class, recordBeanDao);
    }
    
    public void clear() {
        myCurrencyPairDaoConfig.clearIdentityScope();
        recordBeanDaoConfig.clearIdentityScope();
    }

    public MyCurrencyPairDao getMyCurrencyPairDao() {
        return myCurrencyPairDao;
    }

    public RecordBeanDao getRecordBeanDao() {
        return recordBeanDao;
    }

}
