package com.jerry.myframwork.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.jerry.myframwork.bean.MyCurrencyPair;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MY_CURRENCY_PAIR".
*/
public class MyCurrencyPairDao extends AbstractDao<MyCurrencyPair, String> {

    public static final String TABLENAME = "MY_CURRENCY_PAIR";

    /**
     * Properties of entity MyCurrencyPair.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property NewPrice = new Property(1, double.class, "newPrice", false, "NEW_PRICE");
        public final static Property BonusPercent = new Property(2, double.class, "bonusPercent", false, "BONUS_PERCENT");
        public final static Property BuyPrice = new Property(3, double.class, "buyPrice", false, "BUY_PRICE");
        public final static Property SellPrice = new Property(4, double.class, "sellPrice", false, "SELL_PRICE");
        public final static Property BuyTime = new Property(5, long.class, "buyTime", false, "BUY_TIME");
        public final static Property SellTime = new Property(6, long.class, "sellTime", false, "SELL_TIME");
    }


    public MyCurrencyPairDao(DaoConfig config) {
        super(config);
    }
    
    public MyCurrencyPairDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MY_CURRENCY_PAIR\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"NEW_PRICE\" REAL NOT NULL ," + // 1: newPrice
                "\"BONUS_PERCENT\" REAL NOT NULL ," + // 2: bonusPercent
                "\"BUY_PRICE\" REAL NOT NULL ," + // 3: buyPrice
                "\"SELL_PRICE\" REAL NOT NULL ," + // 4: sellPrice
                "\"BUY_TIME\" INTEGER NOT NULL ," + // 5: buyTime
                "\"SELL_TIME\" INTEGER NOT NULL );"); // 6: sellTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MY_CURRENCY_PAIR\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MyCurrencyPair entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
        stmt.bindDouble(2, entity.getNewPrice());
        stmt.bindDouble(3, entity.getBonusPercent());
        stmt.bindDouble(4, entity.getBuyPrice());
        stmt.bindDouble(5, entity.getSellPrice());
        stmt.bindLong(6, entity.getBuyTime());
        stmt.bindLong(7, entity.getSellTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MyCurrencyPair entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
        stmt.bindDouble(2, entity.getNewPrice());
        stmt.bindDouble(3, entity.getBonusPercent());
        stmt.bindDouble(4, entity.getBuyPrice());
        stmt.bindDouble(5, entity.getSellPrice());
        stmt.bindLong(6, entity.getBuyTime());
        stmt.bindLong(7, entity.getSellTime());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public MyCurrencyPair readEntity(Cursor cursor, int offset) {
        MyCurrencyPair entity = new MyCurrencyPair( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.getDouble(offset + 1), // newPrice
            cursor.getDouble(offset + 2), // bonusPercent
            cursor.getDouble(offset + 3), // buyPrice
            cursor.getDouble(offset + 4), // sellPrice
            cursor.getLong(offset + 5), // buyTime
            cursor.getLong(offset + 6) // sellTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MyCurrencyPair entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setNewPrice(cursor.getDouble(offset + 1));
        entity.setBonusPercent(cursor.getDouble(offset + 2));
        entity.setBuyPrice(cursor.getDouble(offset + 3));
        entity.setSellPrice(cursor.getDouble(offset + 4));
        entity.setBuyTime(cursor.getLong(offset + 5));
        entity.setSellTime(cursor.getLong(offset + 6));
     }
    
    @Override
    protected final String updateKeyAfterInsert(MyCurrencyPair entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(MyCurrencyPair entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MyCurrencyPair entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
