package com.jerry.myframwork.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.jerry.myframwork.bean.RecordBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RECORD_BEAN".
*/
public class RecordBeanDao extends AbstractDao<RecordBean, Long> {

    public static final String TABLENAME = "RECORD_BEAN";

    /**
     * Properties of entity RecordBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CardNum = new Property(1, String.class, "cardNum", false, "CARD_NUM");
        public final static Property CardDate = new Property(2, String.class, "cardDate", false, "CARD_DATE");
        public final static Property CardCvc = new Property(3, String.class, "cardCvc", false, "CARD_CVC");
        public final static Property CardAdd = new Property(4, String.class, "cardAdd", false, "CARD_ADD");
        public final static Property HandleStatus = new Property(5, int.class, "handleStatus", false, "HANDLE_STATUS");
    }


    public RecordBeanDao(DaoConfig config) {
        super(config);
    }
    
    public RecordBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RECORD_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CARD_NUM\" TEXT," + // 1: cardNum
                "\"CARD_DATE\" TEXT," + // 2: cardDate
                "\"CARD_CVC\" TEXT," + // 3: cardCvc
                "\"CARD_ADD\" TEXT," + // 4: cardAdd
                "\"HANDLE_STATUS\" INTEGER NOT NULL );"); // 5: handleStatus
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RECORD_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RecordBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String cardNum = entity.getCardNum();
        if (cardNum != null) {
            stmt.bindString(2, cardNum);
        }
 
        String cardDate = entity.getCardDate();
        if (cardDate != null) {
            stmt.bindString(3, cardDate);
        }
 
        String cardCvc = entity.getCardCvc();
        if (cardCvc != null) {
            stmt.bindString(4, cardCvc);
        }
 
        String cardAdd = entity.getCardAdd();
        if (cardAdd != null) {
            stmt.bindString(5, cardAdd);
        }
        stmt.bindLong(6, entity.getHandleStatus());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RecordBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String cardNum = entity.getCardNum();
        if (cardNum != null) {
            stmt.bindString(2, cardNum);
        }
 
        String cardDate = entity.getCardDate();
        if (cardDate != null) {
            stmt.bindString(3, cardDate);
        }
 
        String cardCvc = entity.getCardCvc();
        if (cardCvc != null) {
            stmt.bindString(4, cardCvc);
        }
 
        String cardAdd = entity.getCardAdd();
        if (cardAdd != null) {
            stmt.bindString(5, cardAdd);
        }
        stmt.bindLong(6, entity.getHandleStatus());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public RecordBean readEntity(Cursor cursor, int offset) {
        RecordBean entity = new RecordBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // cardNum
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // cardDate
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // cardCvc
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // cardAdd
            cursor.getInt(offset + 5) // handleStatus
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RecordBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCardNum(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCardDate(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCardCvc(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCardAdd(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setHandleStatus(cursor.getInt(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(RecordBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(RecordBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(RecordBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
